### ISSUE TITLE
字幕问题

### ISSUE THREAD

**Issue by nchuan123** [MingYSub/SubArchive#10]
《变成狗后被喜欢的人捡了》 第3分35秒开始的一句

> Dialogue: 0,0:03:35.48,0:03:38.78,Default,,0,0,0,,这就是电话里说的捡到的猫吗

是不是错了，港澳台的字幕是小狗，看语境应该也是狗

**Comment by MingYSub** [comment]
感谢反馈。发布前确实没有做好校对，目前已完成校对，内嵌、内封会在有片源只后发布。
